### ISSUE TITLE
[P1] 사용자 모니터링 화면 구현 - Backend

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#1]
# ✨Todo✨

# 사용자 모니터링 서버 개발 🔥

## Back
- [x]  Front ID 기반 개인정보 요청 로직 수정
- [x] 모니터링 화면 개인 정보 전송 (이름, 사원번호, 사진)
- [x] 모든 과정 마친 후  [측정 데이터] + 출근 날짜 + 출근 시간 데이터 포함 후 보관 로직 수정
- [x] ERD 점검 후 삭제할 데이터 선별
- [x] 제작된 엔드포인트 정리
- [x] Service 레이어 생성
- [x] 출근 등록 완료 후 SMS 문자 전송
