### ISSUE TITLE
[P1] 사용자 모니터링 화면 구현 - Frontend 

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#14]
# ✨Todo✨

# 사용자 모니터링 화면 개발 🔥

## Front
- [x] 모니터링 화면 구성 (이름, 사원번호, 사진, 음주, 심박수, 온도)
- [x] 안내 메시지 & 안내 음성 출력
- [x] 모니터링 화면 디자인
- [x] 지문 센서 ID 반환 요청
- [x] 사용자 ID 기반 서버로 사용자 데이터 요청
- [x] 사용자 인식 후 소프트웨어 요청 2회 알콜 | 심박수, 체온
- [x] 안내 절차 수정
- [x] 모든 측정 후 출근 완료 화면 및 서버로 출근 요청
- [x] 출근 완료 후 다시 1단계 모니터링 전환
- [x] 응답 코드 101 ~ 103 맞는 퇴근, 퇴근 완료 표시 화면
