### ISSUE TITLE
 [P1] 사용자 모니터링 화면 구현 - SoftWare

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#15]
# ✨Todo✨

# 사용자 측정 센서 탐구 및 개발 🔥

## SoftWare 
- [x] 모니터링 기능 관련 센서 코드 작성
- [x] 센서 반환 값 시리얼 통신으로 라즈베리파이 전달
- [x] 지문 요청 EndPoint 생성
- [x] 알콜 | 체온, 심박수 요청 EndPoint 생성
- [x] 사용자 측정 센서 탐구 및 개발
- [x] 실물 스케치

**Comment by 02present** [comment]
from flask import Flask
import serial

app = Flask(__name__)
ser = serial.Serial('/dev/cu.usbmodem1101', 9600)  # 아두이노가 연결된 시리얼 포트

#지문 엔드포인트
@app.route('/fingerprint', methods=['GET'])
def get_sensor_data_fp():
    fingerprint_value = 0 #임시값 입니다.
    #ser.write(b'ReadSensor\n')  # 아두이노로 센서값 요청
    #sensor_value = ser.readline().strip().decode()  # 아두이노로부터 센서값 읽기
    return fingerprint_value

#음주 엔드포인트
@app.route('/drink', methods=['GET'])
def get_sensor_data_alc():
    ser.write(b'alc\n')  # 아두이노로 센서값 요청
    alcsensor_value = ser.readline().strip().decode()  # 아두이노로부터 센서값 읽기
    return alcsensor_value

#체온 심박 엔드포인트
@app.route('/tempheart', methods=['GET'])
def get_sensor_data_temp():
    ser.write(b'temp\n')  # 아두이노로 센서값 요청
    tempsensor_value = ser.readline().strip().decode()  # 아두이노로부터 센서값 읽기
    return tempsensor_value


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001)
