### ISSUE TITLE
[P1] 사용자 모니터링 화면 구현 - PM

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#30]
# ✨Todo✨

# 사용자 모니터링 PM 🔥

## PM
- [x] 프론트 및 소프트웨어 연동 주기적 보고 및 피드백
- [x] 소프트웨어 Flask 서버 구현 방향 안내
- [x] 라즈베리파이 및 아두이노 -> 프론트 사진 전송 방안 탐색

**Comment by taek2222** [comment]
from flask import Flask, rendertemplate
app = Flask(name)

@app.route("/")
def home():
    return rendertemplate("html파일명.html")

if name=='__main':
    app.run(host='0.0.0.0')

**Comment by CSHJ0711** [comment]
capstone@raspberrypi:~/Desktop $ pip install falsk
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
