### ISSUE TITLE
[P2] 회원 관리 페이지 - Front

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#37]
# ✨Todo✨

# 회원 관리 페이지 🔥

## Front
- [x] 모니터링 화면 산소 포화도 추가

- [x] 회원 관리 페이지 ( 메인 )
  - [x] 페이지 디자인
  - [x] 출력 내용 직위(관리직, 계약직, 일용직) | 사원번호 | 이름 | 나이 | 성별 | 전화번호 | 이메일
- [x] 회원 관리 페이지 ( 상세 )
  - [x] 페이지 디자인
  - [x] 직위 ( 관리직, 계약직, 일용직) | 사원번호 | 이름 | 나이 | 성별 | 전화번호 | 이메일 | 주소 | 입사일자 | 은행 | 계좌번호
  - [x] 아래 하단의 List 형식 근무날짜 | 출근 시간 | 퇴근 시간 | 알코올 | 온도 | 심박 | 산소포화도 | 상태(출근, 퇴근) | 비고
  - [x] 화면 표시 데이터 수정 및 삭제 기능.
