### ISSUE TITLE
[P2] 회원 관리 페이지 구현 - Back

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#38]
# ✨Todo✨

# 회원 관리 페이지 구현 🔥

## Back
- [x] 회원 관리 데이터 추가
- [x] 모니터링 산소포화도 데이터 추가 및 POST 요청에도 기록 수정
- [x] 회원 관리에 필요한 데이터 전송
  - [x] 회원 관리(메인) All GET 요청 생성
  - [x] 회원 관리(상세) 
    - [x] ID 기반 GET 요청 생성
    - [x] ID 기반 PATCH 요청 생성
    - [x] ID 기반 DELETE 요청 생성
