### ISSUE TITLE
[P1] 사용자 모니터링 화면 구현 (2) - SoftWare

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#39]
# ✨Todo✨

# 사용자 모니터링 화면 구현 (2) 🔥

## SoftWare 
- [x] 지문 인식 센서 오작동 없이 구현
- [x] 압력 센서 기반 알코올 측정 개선
- [x] 산소포화도 기반 체온, 심박 측정 개선
- [x] 아두이노 센서 최대한 라즈베리파이로 전환
- [x] 센서 Null 및 쓰레기 값 체크

**Comment by 02present** [comment]
(0430)
지문인식센서 (USB to TTL) : 라즈베리파이 이식 성공, 엔드포인트 생성 완료
산소 & 심박센서(I2C) : 라즈베리파이 이식 성공, 엔드포인트 생성 완료, 프론트팀과 통신 성공.
체온센서(ADC) : 고장으로 주문, 아날로그 데이터 -> 디지털로 변환 부품 주문.
알코올센서(ADC) : 아날로그 데이터 -> 디지털로 변환 부품 주문.
압력센서(ADC) : 아날로그 데이터 -> 디지털로 변환 부품 주문.
미세먼지센서 : 개발 전.
카메라 : 개발 전.

**Comment by 02present** [comment]
(0514)
지문인식센서 (USB to TTL) : 라즈베리파이 이식 성공, 엔드포인트 생성 완료
산소 & 심박센서(I2C) : 라즈베리파이 이식 성공, 엔드포인트 생성 완료, 프론트팀과 통신 성공.
체온센서(ADC) : I2C 통신을 이용하여 통신. 센서 불안정으로 모든 센서 세팅 완료시까지 연결 대기중
알코올센서(ADC) : ADC 이용하여 통신 성공. 기존 아날로그 데이터 (0~1024) 에서 0.01 단위로 변경작업 완료.
압력센서(ADC) : ADC 이용하여 통신 성공하였으나, 바람의 무게는 감지하지 못함.
미세먼지센서 : 개발 전.
카메라 : 개발 전.
조도센서 : 구매예정.
