### ISSUE TITLE
[P2] 회원 관리 페이지 - Back 

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#41]
# ✨Todo✨

# 회원 관리 페이지 구현 🔥

## Back
- [x] DELETE 오류 수정
- [x] PATCH 오류 수정
- [x] 회원 등록 EndPoint 생성
- [x] CORS 정책 수정
- [x] 코드 최적화
