### ISSUE TITLE
[P2] 회원 관리 페이지 (2) - Front 

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#45]
# ✨Todo✨

# 회원 관리 페이지 (2) 🔥

### 회원 관리 (메인)
- [x] 목록 출력 시 사원 번호 순서대로
- [x] 회원 생성 시 전화번호 3칸 분리
- [x] 회원 생성 API 요청 시 전화번호 3칸 합쳐서 전달
- [x] 회원 생성 디자인

### 회원 관리 (상세)
- [x] 데이터 수정 시 사원 번호 고정
- [x] 데이터 수정 시 성별, 직위 선택 방식 변경
- [x] 데이터 목록 비고 삭제
- [x] 메모란 상세 표시 가장 하단으로 수정
- [x] 데이터 표시 (전체, 필터링)
