### ISSUE TITLE
[P2] 회원 관리 페이지 (2) - Back

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#46]
# ✨Todo✨

# 회원 관리 페이지 (2) 🔥

## Back
- [x] 데이터 목록 EndPoint 에러 수정 후 완성
- [x] 데이터 목록 필터링 EndPoint 수정
- [x] ROLLBACK TRANSACTION 기능 추가
- [ ] 코드 최적화

### 추가적 고려 사항
- 통계 표시 구상
