### ISSUE TITLE
[P1] 사용자 모니터링 화면 구현 (3) - SoftWare 

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#47]
# ✨Todo✨

# 사용자 모니터링 화면 구현 (3) 🔥

## SoftWare 
- [x] 압력 센서 + 알코올 측정 기능 완성
- [x] 알코올 측정된 값 기준치
- [x] 통계에 필요한 온-습도, 조도, 미세먼지 센서 확인
- [x] 실물 모델링 작업

**Comment by 02present** [comment]
(0514)
지문인식센서 (USB to TTL) : 라즈베리파이 이식 성공, 엔드포인트 생성 완료
산소 & 심박센서(I2C) : 라즈베리파이 이식 성공, 엔드포인트 생성 완료, 프론트팀과 통신 성공.
체온센서(ADC) : I2C 통신을 이용하여 통신. 센서 불안정으로 모든 센서 세팅 완료시까지 연결 대기중
알코올센서(ADC) : ADC 이용하여 통신 성공. 기존 아날로그 데이터 (0~1024) 에서 0.01 단위로 변경작업 완료.
압력센서(ADC) : ADC 이용하여 통신 성공하였으나, 바람의 무게는 감지하지 못함.
미세먼지센서 : 개발 전.
카메라 : 개발 전.
조도센서 : 구매예정.
