### ISSUE TITLE
[FINAL] PROEJCT - Back

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#58]
# ✨Todo✨

# [FINAL] PROEJCT 🔥

### taek2222
- [x] 온도, 습도, 미세먼지, 조도 값 받는 POST
- [x] 온도, 습도, 미세먼지, 조도 값 전달하는 GET
- [x] 전날 근로자 평균 근로 시간 GET 
- [x] AI 기반 공사장 상태 평가 GET
- [x] 문자 mmHg -> bpm

### chaewon9472
- [x] 출근 현황 값 GET
 - [x] 출근, 결근 데이터 상세보기 GET
- [x] 근로자 알코올 이상자 수 GET
 - [x] 알코올 이상자 데이터 상세보기 GET 
- [x] 근로자 평균 수치 값 GET
- [x] 근로자 종합 데이터 (정상,주의,심각)  GET
- [x] 근로자 종합데이터 상세보기 GET

### 공통 사항
- [x] ROLLBACK TRANSACTION 기능 추가
- [x] 코드 최적화
