### ISSUE TITLE
[FINAL] PROEJCT - Front

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#59]
# ✨Todo✨

# [FINAL] PROEJCT 🔥

## Front
- [x] 모니터링 문제
  - [x] 소프트웨어와 통신 문제
    - [x] 지문 요청 후 반환 값 기반 작동 (만약, 오류 코드 시 되돌아가게)
  - [x] 하단 짤리는 현상
  - [x] 최종적으로 작동 이상 없는지 확인 
- [x] 직원 관리 - 상세 메모 안보이는 현상
- [x] 직원 관리 - 상세 - 수정 직위, 성별 선택형으로 변경
- [x] 데이터 검색 기능 개선 (직원관리, 상세 2개 모두)
- [x] 직원 등록 디자인
- [x] 근로자 평균 <-> 알코올 이상자 위치 변경
- [x] 그래프 1분 단위 최대 10줄
- [x] 출근 현황, 근로자 종합 데이터, 알코올 이상자 ( 상세보기 ) 생성
