### ISSUE TITLE
[FINAL] PROEJCT - Software

### ISSUE THREAD

**Issue by taek2222** [GWNU-Capstone/Safety_Management#60]
# ✨Todo✨

# [FINAL] PROEJCT 🔥

## Software
- [x] 모니터링 관련 문제
  - [x] 지문 센서 오류
  - [x] 지문 센서 20초 이상 대기 시 오류 코드 반환
  - [x] 알코올 센서 기준 값 선별 후 무한 대기로 생성
  - [x] 체온 센서 장착 
  - [x] 체온, 심박수, 산소 포화도 측정 (하나라도 미측정 시 응답 X)
  - [x] 알코올, 산소포화도 소수점 절삭
- [x] 통계에 필요한 온-습도, 조도, 미세먼지 센서 확인
- [x] 실물 모델링 (우드락, 3D 모델링) 출력
- [x] 센서 정리 후 장착 크기 고려 
- [x] 카메라 모듈 장착
- [x] 카메라 스크린샷 촬영 EndPoint 생성

**Comment by 02present** [comment]
0521
지문센서 오류 -> 짧은 시간 내에 너무 많은 요청으로 인한 오류. 최소한 2~3초 정도의 텀을 두고 요청을 보내야 함. (내부 캐시 저장소의 쓰기 문제로, 정상화까지 꽤나 오랜 시간이 걸림. 프론트에서 너무 연속된 요청을 삼가야 함)
알코올 센서 -> 맨 처음 측정된 값과 10% 범위를 벗어난 상태에서 소숫점 둘째자리까지 5회 같아야 리턴. (1.5초 간격) 조건 만족하지 못할 시 무한루프
심박수, 산소포화도, 체온센서 -> 심박수는 30.0 이상, 산소포화도는 90.0 이상, 체온은 30도에서 45도 사이일 때에만 리턴함. 그 외의 결과값이 나온 경우 무한루프

알코올은 소수점 둘째자리까지, 심박과 산소포화도는 소수점 셋째자리까지 출력됨

**Comment by 02present** [comment]
0522
카메라 기능 완료

**Comment by 02present** [comment]
0523
조도센서 연결완료

**Comment by 02present** [comment]
0526

체온센서 연결 완료

**Comment by 02present** [comment]
0527

심박센서 오류 (고장으로 추정)
